/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.company;

import lombok.extern.slf4j.Slf4j;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.core.env.Environment;

import java.net.InetAddress;
import java.net.UnknownHostException;

@SpringBootApplication(scanBasePackages = {"com.company"})
@EnableDiscoveryClient
@EnableFeignClients
@MapperScan(basePackages = "com.company")
@Slf4j
public class App {

public static void main(String[] args) throws UnknownHostException {

    ConfigurableApplicationContext application = SpringApplication.run(App.class, args);
    Environment env = application.getEnvironment();
    String contextPath = env.getProperty("server.servlet.context-path");
    contextPath = contextPath == null ? "" : contextPath;
    log.info("\n----------------------------------------------------------\n\t" +
                    "Application  is running! Access URLs:\n\t" +
                    "Local: \t\t http://localhost:{}{}\n\t" +
                    "External: \t http://{}:{}{}\n\t" +
                    "Doc: \t http://localhost:{}{}/doc.html\n" +
                    "----------------------------------------------------------",
            env.getProperty("server.port"),
            contextPath,

            InetAddress.getLocalHost().getHostAddress(),
            env.getProperty("server.port"),
            contextPath,

            env.getProperty("server.port"),
            contextPath
    );
 }
}
